development:
    adapter:  mysql2 
    database: election-map
    username: election-map
#    password: election-map
    password: k=~B@aArTYb?
    encoding: utf8
#    host: 192.168.1.200
#    port: 3306
    host: 127.0.0.1
    socket: /tmp/mysql.sock
    reconnect: true
    pool: 6

production:
    adapter:  mysql2
    database: election-map
    username: election-map
    password: 
    encoding: utf8
#    host: 192.168.1.200
#    port: 3306
    host: 127.0.0.1
    socket: /tmp/mysql.sock
    reconnect: true
    pool: 6

